# Render static site routing configuration
# Generated: 2026-05-03T21:04:44.765Z
# More specific routes should be listed before catch-all routes

routes:
  - type: rewrite
    source: /product/*
    destination: /product.html
  - type: rewrite
    source: /category/*
    destination: /category.html
